# -*- coding: utf-8 -*-
"""ARITHMETIC OPERATION

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12YNbTiaClNwwzBb4OYuvNTUcaWDdAaV1

SIMPLE ARITHMETIC
"""

a = 5
b = 6
c = a+b
print(c)

"""Simple Arithmetic - Get input from User"""

a = int(input("Enter a value of a: "))
b = int(input("Enter a value of b: "))
add = a+b
sub = a-b
mult = a*b
div = a/b
mod = a%b
print("Sum: %d, Diff: %d, Mult: %d, Div:%5.3f, Mod:%d"%(add,sub,mult,div,mod))

"""Simple Arithmetic - Get Input from user (power)"""

a = 2
b = 3
power =a**b
print(power)

"""STRINGS

Create Strings
"""

a = "python"
b = "language"
print(a)
print(b)

"""Concatanation"""

a = "Hi"
b = " Hello"
print(a+b)

"""Length of String"""

a="hello"
print(len(a))

"""Repeat string"""

a="A"
b=a*5
print(b)

"""String index"""

a="Hello"
print(a[3])
print(a[2:])
print(a[:2])
print(a[-1])
print(a[:-1])
print(a[::2])
print(a[::-1])

"""String Functions"""

a="Master Mind"
print(a.upper())
print(a.lower())

b = a.split()
print(b)
print(b[0])

c="Ak,Suja,Surya"
d=c.split(",")
print(d)
print(d[1])

a="Master mind"
print(f"Welcome to Python {a} !")

"""Create List"""

a = [1,2,3,4,5]
b = ["Hi",4,91.6]
print(a,b)
print(len(a))
print(b[1])
print(a[1:])
print(a[:2])
print(a+b)

"""Insert new elements into the list"""

a = [1,2,3,4,5]
a.append(6)
print(a)

"""Reverse"""

a = [1,2,3,4]
a.reverse()
a

"""nested list"""

a=[1,2,3]
b=[4,5,6]
c=[a,b]
print(c)
print(c[0])
print(c[0][0])

"""DICTIONARIES

creating dictionary and key values
"""

a = {"Name": "Ak", "Age": 26,"Company":["SpaceX","Tesla"]}
a

a = {"Name": "Ak", "Age": 26,"Company":["SpaceX","Tesla"]}
print(a["Name"])
a["Age"] =51
a

b={'Climate':{'Condition':{'Temperature':'30 Degree','Humidity':'70 percentage'}}}
print(b["Climate"]["Condition"]["Temperature"])

print(a.keys())
print(a.values())
print(a.items())

"""TUPLES

creating tuples
"""

a = ("Hello", 22,99.5)
a

print(len(a))
print(a[0])
print(a.index("Hello"))

"""SET"""

a = set()
a.add(30)
a

a.add("HI")
a

b = ["Hi",20,14.5]
set(b)

"""BOOLEAN

"""

a = True

a = 10
b = 5
c = 15
print(a<b)
print(a>b)
print(a==b)
print(a!=b)
print(a<=b)
print(a>=b)
print(a<b and c>a)
print(a<b or c>a)